name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow updating the README
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Medium posts using GitHub Actions
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@kayumuzzaman'
          max_post_count: 3
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://cdn.jsdelivr.net/npm/simple-icons@v8/icons/medium.svg"></a></td><td><strong><a href="$url">$title</a></strong><br/><i>$description</i><br/><sup>Published on $date</sup></td></tr></table>'
          date_format: 'mmmm dd, yyyy'
          comment_tag_name: 'BLOG-POST-LIST'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
