name: Latest blog post workflow
on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow updating the README
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Medium posts using GitHub Actions
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/feed/@kayumuzzaman'
          max_post_count: 5
          template: '[$title]($url) $newline'
          comment_tag_name: 'BLOG-POST-LIST'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
